name: animate_icons
description: This is a plugin with the help of which you can animate between any two icons like we do in AnimatedIcon widget given to us by default.
version: 1.0.2
repository: https://github.com/Aman-Malhotra/animate_icons
homepage: https://github.com/Aman-Malhotra/animate_icons

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
